package ruleimplementations;

import java.util.List;

import protocol.ProtocolMessages;

/**
 * A class that checks whether a move is valid.
 * 
 * Can be used by both the players (clients) and the game (server).
 */

public class MoveValidator {

	BoardUpdater boardUpdater = new BoardUpdater();
	String board;
	
	public boolean processMove(String move, int boardDimension, String theBoard, 
			char color, List<String> prevBoards) {

		board = theBoard;
		
		boolean validity;
		validity = checkValidityBeforeRemoving(move, boardDimension);
		if (validity == false) {
			return false;
		}
		
		int location = Integer.parseInt(move);
		board = theBoard.substring(0, location) + color + theBoard.substring(location + 1);
		board = boardUpdater.determineNewBoard(board, color);
		
		validity = checkValidityAfterRemoving(board, prevBoards);
		
		return validity;
	}
	
	/**
	 * Check whether a non-pass and non-quit move is valid. 
	 * 
	 * It is invalid if:
	 * 1. the move cannot be parsed to an integer
	 * 2. the move is not within the board
	 * 3. the location is not currently empty
	 * 
	 * @param move, a string representation of a move
	 * @param boardDimension, the size (length / height) of a board
	 * 
	 * @return validness, a boolean that is true is the move is valid, otherwise false
	 */
	public boolean checkValidityBeforeRemoving(String move, int boardDimension) {
		
		int location;
		try {
			location = Integer.parseInt(move);
		} catch (NumberFormatException e) {
			return false;
		}
		
		if (location < 0 || location >= boardDimension * boardDimension) {
			return false;
		}
		
		if (board.charAt(location) != ProtocolMessages.UNOCCUPIED) {
			return false;
		}
		
		return true;
	}
	
	/**
	 * Check whether a new board does not create a board that was seen before in the game.
	 * 
	 * @param newBoard, the board that was generated by the move
	 * @param prevBoards, all boards that were seen before
	 * @return validness, a boolean: true if the move does not result in a board seen before
	 */
	public boolean checkValidityAfterRemoving(String newBoard, List<String> prevBoards) {
		
		for (String aPrevBoard : prevBoards) {
			if (newBoard.equals(aPrevBoard)) {
				return false;
			}
		}
		return true;
	}
}
